
db_path=data/cine.db
log_path=data/servidor.log
csv_import_path=data/peliculas_import.csv

admin_default_user=admin
admin_default_pass_hash=240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9

max_intentos_login=3